[target.aarch64-unknown-linux-gnu]
pre-build = [
    "apt-get update -q",
    "DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends apt-utils libssl-dev libsasl2-dev pkg-config",
    "dpkg --add-architecture arm64 && apt-get update -q && apt-get install -y --no-install-recommends libssl-dev:arm64 clang-5.0"
    "curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v26.0/protoc-25.0-linux-x86_64.zip",
    "unzip protoc-25.0-linux-x86_64.zip -d /usr/local",
    "export PATH=\"/usr/local/bin:$PATH\""
]
