[target.aarch64-unknown-linux-gnu]
pre-build = [
    "apt-get update -q",
    "DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends apt-utils libssl-dev libsasl2-dev pkg-config",
    "apt-get install -y --no-install-recommends libclang-dev clang libc6-dev-aarch64-cross gcc-aarch64-linux-gnu"
]
