[target.aarch64-unknown-linux-gnu]
pre-build = [
    "apt-get update -q",
    "DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends apt-utils libssl-dev libsasl2-dev pkg-config",
    
    # Enable ARM64 architecture
    "dpkg --add-architecture arm64 && apt-get update -q",
    
    # Install system dependencies
    "apt-get install -y --no-install-recommends libssl-dev:arm64 unzip",

    # Download and install Clang 16 manually
    "curl -LO https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/clang+llvm-16.0.6-x86_64-linux-gnu-ubuntu-22.04.tar.xz",
    "tar -xf clang+llvm-16.0.6-x86_64-linux-gnu-ubuntu-22.04.tar.xz",
    "mv clang+llvm-16.0.6-x86_64-linux-gnu-ubuntu-22.04 /usr/local/llvm",

    # Set Clang path
    "export PATH=\"/usr/local/llvm/bin:$PATH\"",
    "export CC=/usr/local/llvm/bin/clang",
    "export CXX=/usr/local/llvm/bin/clang++",

    # Verify Clang installation
    "/usr/local/llvm/bin/clang --version",

    # Install Protoc manually
    "curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v25.0/protoc-25.0-linux-x86_64.zip",
    "unzip protoc-25.0-linux-x86_64.zip -d /usr/local",
    "chmod +x /usr/local/bin/protoc",

    # Set environment variables
    "export PATH=\"/usr/local/bin:$PATH\"",
]
