name: Cross Comilation Test

on:
  pull_request:
    paths:
      - .github/workflows/aarch-linux-release.yaml
      - Cargo.toml
      - Cargo.lock
      - flake.nix
      - flake.lock
      - ci/**
      - e2e/**
      - crates/**
      - tools/**

jobs:
  cross-compile-aarch:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Protoc
        uses: heliaxdev/setup-protoc@v2
        with:
          version: "25.0"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies for cross-compile
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            libssl-dev:arm64 \
            pkg-config
      - name: Install Cross
        run: cargo install cross --locked
      - name: Cross Compile
        run: cross build --release --bin hermes --target aarch64-unknown-linux-gnu